### ISSUE TITLE
Make issue after cloning and following the readme instructions

### ISSUE THREAD

**Issue by savaged** [nereusx/md2roff#2]
Really keen to give this a try, however I'm falling at the first few steps. After following the readme instructions when I come to the `make` I get the following:
```
./md2roff --synopsis-style=1 md2roff.md > md2roff.1
groff md2roff.1 -Tpdf -man -P -e > md2roff.1.pdf
groff: can't find 'DESC' file
groff: fatal error: invalid device 'pdf'
make: *** [Makefile:16: md2roff.1.gz] Error 3
```

I'm using Bash on Ubuntu 20.04.3 LTS x86_64.

Keen to get either additional docs or a makefile fix.

Thanks

**Comment by nereusx** [comment]
I dont use debian based distros. I suppose there is missing a package, maybe the ghostscript, maybe something else. The error said that you cannot create pdf file from groff. 
In anycase you do not need the pdf file. Edit the Makefile and remove this line.

**Comment by savaged** [comment]
Nice one! That worked fine. Thank you. I look forward to using your super tool. Thanks
