### ISSUE TITLE
Generated man pages look like a mess with GROFF

### ISSUE THREAD

**Issue by samboy** [nereusx/md2roff#7]
I tried to generate a man page with this, but it looked like a mess when rendered with GNU nroff (groff) version 1.22.4

The source document I tried to render is here:

* https://github.com/samboy/MaraDNS/blob/master/coLunacyDNS/README.md

Issues:

* Warnings about macros
* Hi-bit stuff looks ugly
* Some bulleted items didn’t render in the man page

Everything looks OK in mandoc.

**Comment by nereusx** [comment]
Man pages have specific structure. This document it could translate to other macro package of groff but not man or mdoc. For example the .TH (man page header) record. The specific md uses one sharp titles, that means multiple .TH records. Use only one '#' and '##' for every section. For normal sections like GNU's options use '####'... Now this project is just a utility to translate man-style markdown to groff with man-macro package. Problems with rendering is groff matter (actually your system, probably fonts and terminal emulator settings). For example try the postscript groff output if its looks ugly too. The pdf in this repo are produced with groff, it is another example.

References:
https://man7.org/linux/man-pages/man7/man-pages.7.html

**Comment by samboy** [comment]
Yeah, I was hoping for a quick and dirty way to give that program a man page. Looks like this isn’t that, and while your program is good for making ROFF documents, I already have a system in place for making man pages which I will use instead:

https://github.com/samboy/MaraDNS/blob/master/tools/ej/ej2man
