### ISSUE TITLE
Error when converting inline code

### ISSUE THREAD

**Issue by mohd-akram** [nereusx/md2roff#9]
This bit of markdown fails to convert:

```markdown
[`[x]()`](a)
```

I get this error:

```
.\# roff document
.\# DO NOT MODIFY THIS FILE! It was generated by md2roff
.do mso man.tmac
.TH stdin 7 2023-06-03 document
.UR 
`[x
.UE
inline code (`) didnt closed.
```

**Comment by nereusx** [comment]
I ll try to handle it soon...

FYI:
syntax []() in markdown is link, example: 
```
[github](https://github.com)
```
Your statement is link inside a link...
```
`[[x]]`()(a) should work...
```
It would be nice if markdown had a control character for such cases like '\' character in C.

**Comment by nereusx** [comment]
v1.11 released... get it. The error fixed but still it is a link. You have to use `\\`
Example:
```
\[`[x]()`](a)
```
